spring:
  application:
    name: ${spring.profiles.active}-storage
  cloud:
    compatibility-verifier:
      enabled: false
  main:
    web-application-type: reactive
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:27017/file?authSource=admin
  profiles:
    active: dev

grpc:
  server:
    port: 9090

server:
  http2:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: false