spring:
  application:
    name: ${spring.profiles.active}-storage
  cloud:
    compatibility-verifier:
      enabled: false
  main:
    web-application-type: reactive
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:27017/file?authSource=admin
  profiles:
    active: dev
  r2dbc:
    url: r2dbc:mysql://${mysql.host}:3306/storage
    username: ${RDBMS_USERNAME}
    password: ${RDBMS_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    url: jdbc:mysql://${mysql.host}:3306/auth
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    locations: classpath:db/migration

grpc:
  server:
    port: 9090

server:
  http2:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
  instance:
    prefer-ip-address: false

mysql:
  host: ${RDBMS_URL}
