spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017/file?authSource=admin
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/storage
    username: root
    password: 1234
  cassandra:
    contact-points: localhost
    username: cassandra
    password: cassandra
    schema-action: create_if_not_exists
    port: 9042
    local-datacenter: datacenter1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

mysql:
  host: localhost